# Checkpoint 0

These exercises are a mix of Python and Pandas practice. Most should be no more than a few lines of code!

In [2]:
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]

In [4]:
# get a list containing the last 3 elements of a
b = a[3:]
print(b)
# Yes, you can just type out [4, 5, 6] but we really want to see you demonstrate you know how to use list slicing in Python

[4, 5, 6]

In [12]:
# create a list of numbers from 1 to 20
c = list(range(1,21))
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [15]:
# Now get a list with only the even numbers between 1 and 100
# you may or may not make use of the list you made in the last cell
d = list(range(2, 101, 2))
print(d)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]

In [16]:
# write a function that takes two numbers as arguments
# and returns the first number divided by the second
def division(a:int,b:int):
    return a/b

In [18]:
# fizzbuzz
# you will need to use both iteration and control flow 
# go through all numbers from 1 to 30 in order
# if the number is a multiple of 3, print fizz
# if the number is a multiple of 5, print buzz
# if the number is a multiple of 3 and 5, print fizzbuzz and NOTHING ELSE
# if the number is neither a multiple of 3 nor a multiple of 5, print the number
for num in range(1,31):
    if num % 3 == 0:
        print("fizz")
    elif num % 5 == 0:
        print("buzz")
    elif num % 5 == 0 and num % 3 == 0:
        print("fizzbuzz")
    else:
        print(num)

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizz

In [20]:
# create a dictionary that reflects the following menu pricing (taken from Ahmo's)
# Gyro: $9 
# Burger: $9
# Greek Salad: $8
# Philly Steak: $10
menu = {"Gyro":9,"Burger":9,"Greek Salad":8,"Philly Steak":10}

In [23]:
# load in the "starbucks.csv" dataset
# refer to how we read the cereal.csv dataset in the tutorial
import pandas as pd
df = pd.read_csv("../data/starbucks.csv")

In [27]:
# select all rows with more than and including 400 calories
df_new = df[df['calories'] >= 400]
df_new.head()

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
81,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,400,11.0,7.0,0.2,25,250,61,0,58,15.0,15,2,45,0.0,150.0
83,signature espresso drinks,white chocolate mocha (without whipped cream),Venti Nonfat Milk,450,7.0,6.0,0.0,10,310,78,0,74,19.0,25,2,60,2.0,150.0
84,signature espresso drinks,white chocolate mocha (without whipped cream),2% Milk,510,15.0,9.0,0.2,35,330,77,0,74,19.0,20,4,60,2.0,150.0
85,signature espresso drinks,white chocolate mocha (without whipped cream),Soymilk,460,13.0,6.0,0.0,5,290,70,1,64,16.0,15,2,60,20.0,150.0
128,tazo tea drinks,tazo green tea latte,2% Milk,450,10.0,5.0,0.3,40,230,72,2,71,17.0,25,20,50,6.0,110.0

In [28]:
# select all rows whose vitamin c content is higher than the iron content
df_new1 = df[df['vitamin c'] > df['iron']]
df_new1.head()

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine
11,classic espresso drinks,caff latte,2% Milk,190,7.0,3.5,0.2,30,170,19,0,17,12.0,20,2,40,0.0,150.0
14,classic espresso drinks,caff latte,2% Milk,240,9.0,4.5,0.3,35,220,24,0,22,16.0,25,2,50,0.0,150.0
35,classic espresso drinks,vanilla latte (or other flavoured latte),2% Milk,250,6.0,3.5,0.2,25,150,37,0,35,12.0,20,2,35,0.0,150.0
38,classic espresso drinks,vanilla latte (or other flavoured latte),2% Milk,320,9.0,4.5,0.3,35,200,46,0,44,15.0,25,2,45,0.0,150.0
69,signature espresso drinks,caramel macchiato,2% Milk,240,7.0,3.5,0.2,25,150,34,0,32,10.0,15,2,30,0.0,150.0

In [33]:
# create a new column containing the caffeine per calories of each drink
df['Caffeine per calories'] = df['caffeine'] / df['calories']
df.head()

,beverage_category,beverage,beverage_prep,calories,total fat,trans fat,saturated fat,sodium,total carbohydrates,cholesterol,dietary fibre,sugars,protein,vitamin a,vitamin c,calcium,iron,caffeine,Caffeine per calories
0,coffee,brewed coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0,0,0,0.0,175.0,58.333333
1,coffee,brewed coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0,0,0,0.0,260.0,65.000000
2,coffee,brewed coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,0,0.0,330.0,66.000000
3,coffee,brewed coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0,0,2,0.0,410.0,82.000000
4,classic espresso drinks,caff latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10,0,20,0.0,75.0,1.071429

In [32]:
# what is the average calorie across all items?
print(df['calories'].mean())

193.87190082644628

In [36]:
# how many different categories of beverages are there?
print(df['beverage_category'].nunique())

9

In [37]:
# what is the average # calories for each beverage category?
print(df.groupby('beverage_category')['calories'].mean())

beverage_category
classic espresso drinks             140.172414
coffee                                4.250000
frappuccino blended coffee          276.944444
frappuccino blended crme            233.076923
frappuccino light blended coffee    162.500000
shaken iced beverages               114.444444
signature espresso drinks           250.000000
smoothies                           282.222222
tazo tea drinks                     177.307692
Name: calories, dtype: float64